config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
   resources :users 
   resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :posts do 
     resources :comments
   end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save { self.email = email.downcase }
  before_create :create_activation_digest

  validates :name,  presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 150 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    has_secure_password
                    validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  private 
  
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :logged_in_user, only: [:edit, :update, :destroy]
 before_action :set_user, only: [:show, :edit, :update]
 before_action :correct_user,   only: [:edit, :update]
 before_action :admin_user,     only: :destroy

  def index 
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @posts = @user.posts.paginate(page: params[:page], :per_page => 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "登録したメールアドレスにメールを送信しました。ご確認下さい！"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end


  private

   def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
   end

   def set_user
       @user = User.find(params[:id])
   end


  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper


  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/edit.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">
    <div id = "form">

      <% provide(:title, "Edit user") %>
      <h1 align="center">プロフィールの変更</h1>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages' %>

            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class="field">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation, "Confirmation" %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <div class="field">
              <%= gravatar_for @user %>
              <a href="http://gravatar.com/emails" target="_blank">change</a>
            </div>

            <%= f.submit "Save changes", class: "button button_color button_center" %>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper">
  	
		<% provide(:title, 'All users') %>
		
		<div id = "form">

			<h1 align="center">全ユーザー</h1>

			<hr class = "line">

		<%= will_paginate %>

				<div id= "users" >
					<% @users.each do |user| %>
						<div class = "box">
							<%= gravatar_for user, size: 50 %><br>
						  	<%= link_to user.name, user %>

							  <% if !current_user.nil? && current_user.admin? && !current_user?(user) %>
							    | <%= link_to "delete", user, method: :delete,
							                                  data: { confirm: "You sure?" } %>
							  <% end %>
						</div>
					<% end %>
				</div>

		<%= will_paginate %>

		</div>
		
	</div>
</div>

app/views/users/new.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">

    <% provide(:title, 'Signup') %>
    <h1 align="center">新規登録</h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages' %>

          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
  
          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "Create", class: "button button_color button_center" %>
        <% end %>

        <hr class = "line-form">

        <div class = "action">
              <p>アカウントをお持ちの方は<%= link_to "ログインへ", login_path %></p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">

	<% provide(:title, @user.name) %>
	<div class="row">
	  <div class="col-md-12">
	  		<div class="profile">
		      <h1 class = "left">
		        <%= gravatar_for @user %>
		        <% if current_user?(@user) %>
		        	<%= link_to @user.name, edit_user_path(@user) %>
		        <% else %>
		        	<%= @user.name %>
		        <% end %>
        	  </h1>
			</div>
			<div class="right">
				<div class="post-button">
					<% if current_user?(@user) %>
		      			<%= link_to "記事投稿", new_post_path, class: "button button_color button_center"%>
		      		<% end %>
		      	</div>
		    </div>
	  </div>
	 </div>

	<div class="user-show">
		<% if @user.posts.any? %>
		   <% @posts.each do |post| %>

		   		<div class = "user-title">
				  	<h4><%= link_to post.title, post_path(post) %></h4>
				</div>
				<div class="user-description">
				  	<%= truncate(post.description, length: 80) %>
				</div>
				<div class="user-time">
				  	投稿時間: <%= time_ago_in_words(post.created_at) %> ago
				</div>
			<% end %>
		<% else %>
			<p>まだ投稿はありません。</p>
		<% end %>
	</div>
	
	<div class="center">
		<%= will_paginate @posts %>
	</div>
  </div>
</div>