config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
   resources :users 
   resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :posts do 
     resources :comments
   end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  #validates :user_id, presences: true
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validate :picture_size

    private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 	before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
 	before_action :set_post, only: [:show, :edit, :update, :destroy]


	def new 
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)
    	if @post.save
    		flash[:success] = "投稿が完了しました。"
      		redirect_to post_path(@post)
    	else
      	render 'new'
    	end
	end

	def show

	end

	def edit

	end

	def update
		if @post.update(post_params)
			flash[:success] = "編集が完了しました。"
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to user_path(current_user)
	end


	private

	   def set_post
	   	  @post = Post.find(params[:id])
	   end

	   def post_params
	      params.require(:post).permit(:title, :description, :picture)
	   end

	   def logged_in_user
    		unless logged_in?
      		store_location
      		flash[:danger] = "ログインしてください"
      		redirect_to login_url
       end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
      <div class="row">
        <div class="col-md-6 col-md-offset-3">

        <%= form_for(@post) do |f| %>
          
          <div class="field">
            <%= f.label :title %><br />
            <%= f.text_field :title, autofocus: true %>
          </div>
        
          <div class="field">
            <%= f.label :description %><br />
            <%= f.text_area :description %>
          </div>

          <div class="field">
             <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
          </div>
        
          <div class="actions">
            <%= f.submit class: "button button_color button_center" %>
          </div>
        <% end %>

        </div>
      </div>

app/views/posts/edit.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">  

    <h1 align = "center">投稿編集</h1>
    
    <%= render 'form' %>
    
  </div>
</div>

app/views/posts/new.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">  

    <h1 align = "center">新規投稿</h1>
    
      <%= render 'form' %>
    
  </div>
</div>


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/posts/show.html.erb
<div class = "bootstrap-padding">
  <div class = "wrapper-skinny">  

  	<div class="show">


		<div id = "center">
			<%= image_tag @post.picture.url, :class => "show-picture" if @post.picture? %>
		</div>

		<div class="show-title">
			<h1><%= @post.title %></h1>
		</div>

		<div class="show-description">
			<%= @post.description %>
			
			<% if current_user?(@post.user) %>
			<hr class = "show-line">
			<%= link_to "記事の編集", edit_post_path(@post) %> / <%= link_to "記事の削除", post_path(@post), method: :delete %> 
			<% end %>

		</div>


		<div class="comment-title">
			<h5><b>コメント欄</b>
			(コメントはログイン、登録しないと投稿出来ません。)</h5>
		</div>


		<% @post.comments.each do |comment| %>
			<div class="comment-commenter">
				コメントした人: <%= link_to comment.commenter, user_path(comment.id) %>
				<!-- 後で確認　-->
			</div>
			<div class="comment-description">
				<%= comment.description %>
			</div>

			<% unless current_user.nil? %>
				<% if comment.commenter == current_user.name %>
					<%= link_to "削除", post_comment_path(@post, comment), method: :delete %>
				<% end %>
			<% end %>

			<hr class = "show-line">


		<% end %>

		<div class="new-comment">
			<% if logged_in? %>
				<p>新規コメント</p>

				<%= form_for [@post, @post.comments.build] do |f| %>
						<%= f.hidden_field :commenter, value: current_user.name %>
					<div class="field">
						<%= f.text_area :description %>
					</div>

					<%= f.submit "コメントする", class: "button button_color button_center" %>

				<% end %>
			<% end %> 
		</div>


		<div class = "left back-class">	
				<%= link_to "<<Back", :back %>
			</div>

	</div>


  </div>
</div>